
package com.jk.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSBookService", targetNamespace = "http://book.ws.jk.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSBookService {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test2", targetNamespace = "http://book.ws.jk.com/", className = "com.Test2")
    @ResponseWrapper(localName = "test2Response", targetNamespace = "http://book.ws.jk.com/", className = "com.Test2Response")
    public int test2();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test3", targetNamespace = "http://book.ws.jk.com/", className = "com.Test3")
    @ResponseWrapper(localName = "test3Response", targetNamespace = "http://book.ws.jk.com/", className = "com.Test3Response")
    public String test3(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod(operationName = "TheFirstMethod")
    @RequestWrapper(localName = "TheFirstMethod", targetNamespace = "http://book.ws.jk.com/", className = "com.TheFirstMethod")
    @ResponseWrapper(localName = "TheFirstMethodResponse", targetNamespace = "http://book.ws.jk.com/", className = "com.TheFirstMethodResponse")
    public void theFirstMethod();

}
